[versions]
agp = "8.3.0"
kotlin = "1.9.0"
junit = "5.9.0"
mockk = "1.13.10"
ldSignaturesJava = "1.5.0"
bouncyCastle = "1.70"
jsonldCommonJava = "1.8.0"
nimbusJoseJwt = "9.40"
springWeb = "5.0.20.RELEASE"
titaniumJsonLd = "1.3.1"
okHttp = "4.1.0"
dokka = "1.9.20"
coreKtx = "1.13.1"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.5"
activityCompose = "1.9.2"
composeBom = "2024.04.01"
orgJson = "20240303"
sonarqube = "5.1.0.4872"
jacksonAnnotations = "2.14.0"
jacksonModuleKotlin = "2.14.0"
mockWebServer = "4.12.0"
annotationJvm = "1.9.1"
cbor = "0.9"
identity = "20231002"

[libraries]
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
ldSignaturesJava = { group = "info.weboftrust", name = "ld-signatures-java", version.ref = "ldSignaturesJava" }
titaniumJsonLd = { group = "com.apicatalog", name = "titanium-json-ld-jre8", version.ref = "titaniumJsonLd" }
okHttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
bouncyCastle = { group = "org.bouncycastle", name = "bcprov-jdk15to18", version.ref = "bouncyCastle" }
jsonldCommonJava = { group = "decentralized-identity", name = "jsonld-common-java", version.ref = "jsonldCommonJava" }
nimbusJoseJwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "nimbusJoseJwt" }
springWeb = { group = "org.springframework", name = "spring-web", version.ref = "springWeb" }
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
extJunit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
lifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui = { group = "androidx.compose.ui", name = "ui" }
uiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
orgJson = { group = "org.json", name = "json", version.ref="orgJson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jacksonAnnotations" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jacksonAnnotations" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonAnnotations" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonModuleKotlin" }
mockWebServer = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockWebServer" }
annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
cbor = { group = "co.nstant.in", name = "cbor", version.ref = "cbor" }
identity = { group = "com.android.identity", name = "identity-credential", version.ref = "identity" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
